In [ ]:
import pandas as pd
import numpy as np

In [26]:
car = pd.read_csv('otomoto_test.csv', sep=';')

In [27]:
car.head()

brand    model  year  mileage   price
0   Subaru  OUTBACK  2015    68209   86900
1  Renault   Scenic  2011   232400   16500
2  Renault   Espace  2015   181788   73900
3      BMW  Seria 5  2017   119244  179799
4  Renault   Koleos  2014   123000   39000

In [28]:
car.shape

(13730, 5)

In [29]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13730 entries, 0 to 13729
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   brand    13730 non-null  object
 1   model    13730 non-null  object
 2   year     13730 non-null  int64 
 3   mileage  13730 non-null  int64 
 4   price    13730 non-null  int64 
dtypes: int64(3), object(2)
memory usage: 536.5+ KB


In [16]:
car['year'].unique()

array([2015, 2011, 2017, 2014, 2016, 2021, 2018, 2019, 2008, 2003, 1988,
       2006, 2013, 2012, 2002, 2020, 2004, 1997, 2010, 2009, 2005, 2001,
       2000, 2007, 1996, 1985, 1992, 1999, 1968, 1998, 1989, 1995, 1965,
       1984, 1983, 2022, 1981, 1962, 1991, 1980, 1963, 1993, 1994, 1979,
       1987, 1951, 1990, 1969, 1974, 1986, 1958], dtype=int64)

In [18]:
car['price'].unique()

array([ 86900,  16500,  73900, ...,  31300, 250000, 109737], dtype=int64)

In [30]:
car['mileage'].unique()

array([ 68209, 232400, 181788, ...,  54873, 421000, 143700], dtype=int64)

In [31]:
car.describe()

year        mileage          price
count  13730.00000   13730.000000   13730.000000
mean    2013.49126  129643.973489   75688.516387
std        5.74539   90629.145886   82289.770221
min     1951.00000       0.000000    2000.000000
25%     2010.00000   56600.000000   26900.000000
50%     2014.00000  127700.000000   49900.000000
75%     2018.00000  190000.000000   89799.000000
max     2022.00000  999999.000000  950000.000000

In [35]:
X=car.drop(columns='price')
y=car['price']
import sys
!{sys.executable} -m pip install sklearn

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1320 sha256=b7b87cb754e2488ebe79547eb3814e97c324e3c34ad80e39a16c506108d959c8
  Stored in directory: c:\users\advni\appdata\local\pip\cache\wheels\22\0b\40\fd3f795caaa1fb4c6cb738bc1f56100be1e57da95849bfc897
Successfully built sklearn


In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [40]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [38]:
ohe = OneHotEncoder()
ohe.fit(X[['brand', 'model']])

OneHotEncoder()

In [46]:
ohe.categories_

[array(['Abarth', 'Aixam', 'Alfa Romeo', 'Audi', 'BMW', 'BMW-ALPINA',
        'Chevrolet', 'Chrysler', 'Citroën', 'DS Automobiles', 'Dacia',
        'Daihatsu', 'Dodge', 'Ferrari', 'Fiat', 'Ford', 'GMC', 'Honda',
        'Hummer', 'Hyundai', 'Infiniti', 'Inny', 'Isuzu', 'Iveco',
        'Jaguar', 'Jeep', 'Kia', 'Lancia', 'Land Rover', 'Lexus',
        'Lincoln', 'MINI', 'Maserati', 'Mazda', 'Mercedes-Benz',
        'Microcar', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Opel',
        'Peugeot', 'Polonez', 'Porsche', 'RAM', 'Renault', 'Rover', 'Saab',
        'Seat', 'Smart', 'SsangYong', 'Subaru', 'Suzuki', 'Tesla',
        'Toyota', 'Uaz', 'Volkswagen', 'Volvo', 'Škoda'], dtype=object),
 array(['09.mar', '100', '1007', '107', '125p', '126', '147', '1500',
        '159', '166', '2', '200', '2008', '206', '206 plus', '207',
        '207 CC', '208', '25', '3', '3008', '301', '307', '308', '370 Z',
        '3GT', '4-Runner', '4008', '407', '469 B', '5', '500', '5008',
        '500L', '500X', 

In [47]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['brand', 'model']), remainder='passthrough')

In [48]:
lr = LinearRegression()

In [49]:
pipe = make_pipeline(column_trans, lr)

In [50]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Abarth', 'Aixam', 'Alfa Romeo', 'Audi', 'BMW', 'BMW-ALPINA',
       'Chevrolet', 'Chrysler', 'Citroën', 'DS Automobiles', 'Dacia',
       'Daihatsu', 'Dodge', 'Ferrari', 'Fiat', 'Ford', 'GMC', 'Honda',
       'Hummer', 'Hyundai', 'Infiniti', 'Inny', '...
       'W201 (190)', 'Wrangler', 'X-Trail', 'X1', 'X2', 'X3', 'X3 M',
       'X4', 'X5', 'X5 M', 'X6', 'X6 M', 'X7', 'XC 40', 'XC 60', 'XC 70',
       'XC 90', 'XCeed', 'XF', 'XJ', 'XK8', 'XV', 'Xsara',
       'Xsara Picasso', 'Yaris', 'Yaris Verso', 'Yeti', 'Ypsilon', 'Z3',
       'Z4', 'Zafira', 'e-tron', 'e-tron GT', 'i10', 'i20', 'i3', 'i30 N',
       'i4', 'i40', 'i8', 'iOn', 'ix20', 'ix35', 'ix55', 'up!'],
      dtype=object)]),
                                                  ['brand

In [51]:
y_pred = pipe.predict(X_test)

In [52]:
y_pred

array([ 35743.11810292,  88185.29447385,  10580.41924682, ...,
        36420.75954597, 144740.47306592, 128376.54202595])

In [53]:
r2_score(y_test, y_pred)

0.7566337157896288

In [54]:
scores=[]
for i in range(1000):
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans, lr)
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    scores.append(r2_score(y_test, y_pred))

In [57]:
import numpy as np
np.argmax(scores)

508

In [58]:
scores[np.argmax(scores)]

0.8187771589063046

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans, lr)
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
scores.append(r2_score(y_test, y_pred))
r2_score(y_test, y_pred)

0.8187771589063046

In [60]:
import pickle

In [61]:
pickle.dump(pipe, open('LinearRegressionModel.pkl', 'wb'))

In [62]:
pipe.predict(pd.DataFrame([['BMW', 'X4', 2016, 100000]], columns=['brand', 'model', 'year', 'mileage']))

array([196127.1214188])